---
- name: backup | Create backup script
  ansible.builtin.template:
    src: "backup/gitlab_backup.sh.j2"
    dest: "/usr/local/sbin/gitlab_backup.sh"
    owner: "root"
    group: "root"
    mode: "0700"

- name: backup | Create backup config script
  ansible.builtin.template:
    src: "backup/gitlab_backup.conf.sh.j2"
    dest: "/etc/gitlab/gitlab_backup.conf.sh"
    owner: "root"
    group: "root"
    mode: "0600"

- name: backup | Create Gitlab backup cron
  ansible.builtin.cron:
    name: "gitlab-backup"
    minute: "{{ gitlab_backup_cron.minute }}"
    hour: "{{ gitlab_backup_cron.hour }}"
    day: "{{ gitlab_backup_cron.day }}"
    weekday: "{{ gitlab_backup_cron.weekday }}"
    month: "{{ gitlab_backup_cron.month }}"
    job: "/usr/local/sbin/gitlab_backup.sh"
