---

- name: Include distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_system }}.yml'
    - 'default.yml'

- name: Add Gitlab repository
  ansible.builtin.include_tasks: repository.yml

- name: Install Gitlab
  ansible.builtin.include_tasks: install.yml

- name: Install Gitlab backup scripts
  ansible.builtin.include_tasks: backup.yml
  when: gitlab_backup_enable
