---
molecule_exceptions:
  - variation: debian11
    reason: "No official packages"
  - variation: fedora33
    reason: "No official packages"
  - variation: fedora34
    reason: "No official packages"
  - variation: fedora35
    reason: "No official packages"
  - variation: rockylinux8
    reason: "No official packages"
  - variation: amazonlinux
    reason: "No official packages"

molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current", "next"]
    platforms:
      - "debian9"
      - "debian10"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      - "ubi8"
      - "almalinux8"
