---
- name: Restart Gitlab
  ansible.builtin.command: gitlab-ctl reconfigure
  register: gitlab_restart
  no-changed-when: false
  failed_when:
    - gitlab_restart.rc != 0
    - not gitlab_restart_handler_ignore_failure
